"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.safeList = void 0;
exports.safeList = {
    background: true,
    'background-color': true,
    'background-image': true,
    'background-repeat': ['repeat', 'repeat-x', 'repeat-y', 'no-repeat'],
    'background-position': true,
    'background-size': true,
    border: true,
    'border-bottom': true,
    'border-bottom-left-radius': true,
    'border-bottom-right-radius': true,
    'border-collapse': ['separate', 'collapse'],
    'border-color': true,
    'border-left': true,
    'border-radius': true,
    'border-right': true,
    'border-style': ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
    'border-top': true,
    'border-top-left-radius': true,
    'border-top-right-radius': true,
    'border-width': true,
    bottom: true,
    'box-shadow': true,
    'box-sizing': ['content-box', 'border-box'],
    color: true,
    clear: ['left', 'right', 'both', 'none'],
    cursor: true,
    display: ['none', 'block', 'inline', 'inline-block', 'list-item', 'table', 'table-cell', 'table-row'],
    height: true,
    float: ['none', 'left', 'right'],
    font: true,
    'font-family': true,
    'font-size': true,
    'font-style': true,
    'font-weight': ['normal', 'bold', 'lighter', 'bolder', '100', '200', '300', '400', '500', '600', '700', '800', '900'],
    left: true,
    'letter-spacing': true,
    'line-height': true,
    'list-style': true,
    'list-style-type': true,
    margin: true,
    'margin-bottom': true,
    'margin-left': true,
    'margin-right': true,
    'margin-top': true,
    'max-height': true,
    'max-width': true,
    'min-height': true,
    'min-width': true,
    overflow: ['visible', 'hidden', 'scroll', 'auto'],
    'overflow-wrap': ['normal', 'break-word'],
    padding: true,
    'padding-bottom': true,
    'padding-left': true,
    'padding-right': true,
    'padding-top': true,
    position: ['absolute', 'relative', 'static', 'fixed'],
    right: true,
    src: true,
    'text-overflow': ['clip', 'ellipsis'],
    'text-align': ['left', 'center', 'right', 'justify'],
    'text-decoration': ['none', 'underline', 'overline', 'line-through', 'underline overline', 'underline line-through', 'overline line-through'],
    'text-shadow': true,
    'text-transform': ['none', 'uppercase', 'lowercase', 'capitalize'],
    'text-wrap': ['normal', 'nowrap', 'wrap'],
    'text-wrap-mode': ['none', 'character', 'word', 'sentence', 'full-width'],
    'text-wrap-option': ['none', 'character', 'word', 'sentence', 'full-width'],
    top: true,
    'vertical-align': ['baseline', 'sub', 'super', 'top', 'text-top', 'middle', 'bottom', 'text-bottom'],
    visibility: ['visible', 'hidden', 'collapse'],
    'white-space': ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line'],
    width: true,
    'word-spacing': true,
    'z-index': true,
};
//# sourceMappingURL=rules.js.map